Homework 4, task 2. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #13
Opened 2021-04-04 03:30 UTC by ubuntuegor

2021-04-07 12:49 UTC, cupertank requested changes
В общем, давай ты сделаешь всё рекурсивно и без parent. Скажу честно, это довольно трудно проверять, потому что это трудно читать, если будут вопросы и предложения пиши

2021-04-07 12:49 UTC, cupertank commented on src/main/kotlin/homework4/AvlMapNode.kt
> +internal class AvlMapNode<K, V>(override val key: K, override var value: V) : MutableMap.MutableEntry<K, V> {
Мне кажется, что у тебя должно быть private var у value, изменения должны проходить только через функцию setValue и наружу торчать override с val

2021-04-07 12:49 UTC, cupertank commented on src/main/kotlin/homework4/AvlMapNode.kt
> +        val savedRightChild = this.rightChild as AvlMapNode
Стой стой, что за касты? К чему вообще? Если тебе нужно победить nullable и ты уверен, что его не будет, то ставь два знака восклицания в конце

2021-04-07 12:49 UTC, cupertank commented on src/main/kotlin/homework4/AvlMapNode.kt
> +    var parent: AvlMapNode<K, V>? = null
А зачем тебе вообще хранить родителя? Всё что с ним связано можно же просто рекурсивно делать

2021-04-07 12:49 UTC, cupertank commented on src/main/kotlin/homework4/AvlMapNode.kt
> +    var height = 0
мне кажется это должно быть private, а если тебе это нужно где-то снаружи, то у тебя должно быть отдельный паблик val с геттером

2021-04-07 12:49 UTC, cupertank commented on src/main/kotlin/homework4/AvlMapNode.kt
> +    var rightChild: AvlMapNode<K, V>? = null
мне кажется это тоже должно быть private

2021-04-07 12:49 UTC, cupertank commented on src/main/kotlin/homework4/AvlMapNode.kt
> +    var parent: AvlMapNode<K, V>? = null
А....
У тебя всё нерекурсивно..................................................

2021-04-07 12:49 UTC, cupertank commented on src/main/kotlin/homework4/AvlMap.kt
> +class AvlMap<K : Comparable<K>, V> : MutableMap<K, V> {
Мне кажется, что не стоит разделять это вот так. Пускай у тебя AvlMapTree реализует MutableMap. Не нужно прокси классов таких делать.

2021-04-09 20:41 UTC, cupertank requested changes
У тебя всё хорошо, но ты зачем-то слишком закручиваешь архитектуру там, где это не надо

2021-04-09 20:41 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +    val entry = AvlMapEntry(key, value)
Объедени AvlNode и AvlMapEntry, зачем тебе отдельный прокси класс...

2021-04-09 20:41 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +
Сделай это приватным, функции добавления и удаления ты можешь унести сюда и просто дергать у рута в AvlMap

2021-04-09 20:41 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +internal class AvlNode<K : Comparable<K>, V>(val key: K, value: V) {
Почему internal?

2021-04-09 20:42 UTC, cupertank commented
Просто энивэй если ты сделаешь сложнее архитектуру, то никому особо легче не станет))
Упрощай, это же котлин

2021-04-09 21:35 UTC, ubuntuegor commented on src/main/kotlin/homework4/AvlNode.kt
> +internal class AvlNode<K : Comparable<K>, V>(val key: K, value: V) {
Не думаю, что какому-то юзеру будет интересно из другого пакета смотреть на класс, который отвечает за ноду авл дерева, когда ему нужен map

2021-04-09 21:38 UTC, ubuntuegor commented on src/main/kotlin/homework4/AvlNode.kt
> +    val entry = AvlMapEntry(key, value)
Ну логика такая, что AvlNode - это именно вершина дерева, с детьми, функциями работы с детьми и т.д., а AvlMapEntry это ближе к мапу, отвечает именно за пару ключ-значение, их хранение и перезапись. Плюс MutableEntry нужно отдавать в MutableMap.entries. Если сами ноды наследовать от MutableEntry, то придется юзеру отдавать всю ноду, с детьми, высотой, и т.п. (по крайней мере я так понял тебе в прошлый раз это не понравилось, мол height в ноде был не приватным)

2021-04-09 21:46 UTC, ubuntuegor commented on src/main/kotlin/homework4/AvlNode.kt
> +    val entry = AvlMapEntry(key, value)
Хотя в entries по идее тип возвращенного значения урезается до MutableEntry, и никакие лишние поля, не заданные в этом интерфейсе видны не будут, но тогда думаю надо у AvlNode оставить internal, чтобы нельзя было извне к нему кастануть

2021-04-09 21:50 UTC, ubuntuegor commented
Ммм оаоа котлин

2021-04-10 09:28 UTC, cupertank commented on src/main/kotlin/homework4/AvlNode.kt
> +internal class AvlNode<K : Comparable<K>, V>(val key: K, value: V) {
почему бы и нет

2021-04-20 00:07 UTC, cupertank approved these changes

2021-04-20 00:07 UTC, merged