Homework 5, task 1. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #14
Opened 2021-04-05 23:53 UTC by ubuntuegor

2021-04-13 17:54 UTC, SpirinEgor requested changes

2021-04-13 17:54 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            val parenthesisStack = mutableListOf<Unit>()
Можно просто число использовать. На открывающую скобку увеличиваешь счётчик, на закрывающую -- уменьшаешь. В конце должен остаться 0, во время работы не должно стать меньше 0.

2021-04-13 17:54 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            val parenthesisStack = mutableListOf<Unit>()
Сейчас это выглядит странно. Какой-то стек, куда зачем-то пустышки кладутся.

2021-04-13 17:54 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +                    element += it.toString()
Такая штука неэффективна в силу не изменяемости строк в Котлине. Ты к тому же постоянно в строку кастуешь символ. Посмотри в сторону `StringBuilder`. Во-первых, избавишься от `var` у `element`, во-вторых там есть необходимый `append`.

2021-04-13 17:54 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            if (input[0] != '(') return IntegerNode(input.toInt())
Проверка выглядит не очень надежно, можно воспользоваться `toIntOrNull`

2021-04-13 18:44 UTC, ubuntuegor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            if (input[0] != '(') return IntegerNode(input.toInt())
Не понял. Если там не число и не выражение в скобках, то входные данные некорректны, программу мы дальше исполнять не можем и toInt вылетит с ошибкой, вроде всё как положено.

2021-04-14 17:18 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            if (input[0] != '(') return IntegerNode(input.toInt())
То есть на самом деле проверка выполняется в 2 местах: сначала в if, а потом неявно при касте. Звучит странно.

2021-04-14 17:22 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            if (input[0] != '(') return IntegerNode(input.toInt())
И как верно ты упомянул, во втором случае вылетит ошибка. Это ошибка прилетит пользователю в лицо, он свернется калачиком и заплачет, потому что ничего не поймёт :(

Идеальный подход, как мне кажется:
- Убрать крайние скобки, если они есть
- Попробовать кастануть в int, если удалось, то создаёшь лист
- Если не удалось, то пытаешься распарсить выражение
- Если снова не удалось, то пишешь пользователю, что в таком то месте он неправильно выражение написал

Последний пункт в данной задаче можно не рассматривать, достаточно просто завершиться со словами "я не могу".

2021-04-14 17:24 UTC, SpirinEgor reviewed
Ответил на комментарии

2021-04-14 17:24 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            if (parenthesisBalance < 0) throw IllegalArgumentException("Unexpected close bracket")
А это точно должно быть здесь, а не после каждого уменьшения?

2021-04-14 17:24 UTC, SpirinEgor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            if (parenthesisBalance < 0) throw IllegalArgumentException("Unexpected close bracket")
Понятно, что на работоспособность не влияет, скорее аккуратность обработки.

2021-04-15 00:25 UTC, ubuntuegor commented on src/main/kotlin/homework5/ExpressionTree.kt
> +            if (input[0] != '(') return IntegerNode(input.toInt())
А ошибки - это в смысле любые эксепшены? Мне тоже кажется, что это не очень красиво, когда вылетает огромный стек трейс кровавого цвета. Но если под дружелюбностью иметь в виду только полезные сообщения у выпавших в консоль эксепшенов, то в случае `toInt` вроде всё не так плохо, он даже показывает, какую строку он не смог спарсить. Да и в условии этой задачи вообще гарантировалось, что пользователь всё правильно ввёл)

2021-04-15 15:40 UTC, SpirinEgor approved these changes

2021-04-15 15:41 UTC, merged