Homework 5, task 2: Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #15
Opened 2021-04-13 18:20 UTC by ubuntuegor

2021-04-14 19:02 UTC, SpirinEgor requested changes
Если какие-то вопросы, то быстрее будет через телеграмм спросить

2021-04-14 19:02 UTC, SpirinEgor commented on src/main/kotlin/homework5/HashMap.kt
> +    private fun initBuckets(newSize: Int = buckets.size) {
А это значение будет каждый раз вычисляться или только раз при создание объекта (то есть 0)?

2021-04-14 19:02 UTC, SpirinEgor commented on src/main/kotlin/homework5/HashMap.kt
> +        }
Я бы так предложил:
```
val conflictCount = buckets.count { it.size > 1 }
val maxBucketSize = buckets.map { it.size }.max
```
Во втором случае может ещё поможет `maxByOrNull`, но я неуверен, надо проверять

2021-04-14 19:02 UTC, SpirinEgor commented on src/main/kotlin/homework5/actions.kt
> +    val map: HashMap<String, String>
Мне не очень нравится, что он тут хранится. У тебя действия привязаны к конкретной мапе. Хотя по факту они выполняются над ней. Логичнее было бы передавать в `perform` мапу, над которой надо сделать действие.

2021-04-14 19:02 UTC, SpirinEgor commented on src/main/kotlin/homework5/actions.kt
> +        """.trimIndent()
А теперь представь, сколько кода надо добавить, если появится новая хеш функция.
Обычно создают функцию `getAvailableHashFunctions`, которая возвращает коллекцию из функций. У каждого есть имя, которое выводится, а потом мапится в нужную реализацию.

2021-04-14 19:02 UTC, SpirinEgor commented on src/main/kotlin/homework5/task2.kt
> +            'e' -> return false
Это что-то страшное :)
Добавь в интерфейс action название, а потом просто проходись циклом по доступным и сравнивай с вводом (аналогично хеш-функциям).

2021-04-15 00:58 UTC, ubuntuegor commented on src/main/kotlin/homework5/HashMap.kt
> +    private fun initBuckets(newSize: Int = buckets.size) {
Судя по тому, что всё работает - вычисляется каждый раз.
(Этот метод вызывается без агрументов в сеттере `hashWrapper`, который используется в `ChangeHashFunctionAction`, который в свою очередь покрыт автоматическим тестом).

2021-04-15 01:04 UTC, ubuntuegor commented on src/main/kotlin/homework5/task2.kt
> +            'e' -> return false
А в Котлине возможно вообще хранить классы в коллекции? Чтобы вот, можно было пробежаться по ним, посмотреть статические поля, а потом создать инстанс выбранного. А то я что-то не нашел. Но для этой задачи кажется можно всё переделать в `object`-ы / функции, тем более что мы экшны решили отвязать от конкретного мапа.

2021-04-15 02:27 UTC, ubuntuegor commented on src/main/kotlin/homework5/HashMap.kt
> +    private fun initBuckets(newSize: Int = buckets.size) {
Будет вычисляться, в документации даже такой [пример](https://kotlinlang.org/docs/functions.html#default-arguments) есть. Ну и иначе функционал смены хэш-функции бы всё ломал, а он, кажется, нормально работает)

2021-04-15 15:47 UTC, SpirinEgor approved these changes

2021-04-15 15:47 UTC, merged