Homework 6, task 1. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #17
Opened 2021-04-23 03:10 UTC by ubuntuegor

2021-05-04 18:35 UTC, elena-lyulina requested changes
Очень крутое приложение с графиками, красиво и удобно, спасибо!

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +    private const val maxElementCount = 100000
константы большими буквами должны писаться https://kotlinlang.org/docs/coding-conventions.html#property-names, поправь везде

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +import tornadofx.launch
такие длинные импорты обычно сворачиваются в один wildcard import, идея умеет делать это самостоятельно, попробуй вызвать optimize imports https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#1b4a9305

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +    }
init должен идти после объявления свойств https://kotlinlang.org/docs/coding-conventions.html#class-layout, а не в конце класса

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +    }
и посмотри в других классах, что у тебя соблюдается class layout

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +    private fun createRandomList(size: Int) = (1..size).shuffled()
используй Random лучше

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorter.kt
> +        get() = _result
если ты хочешь оставить только геттер у свойства, то можно сделать у него приватный сет, вот так:
```
    lateinit var result: List<T>
        private set
```

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorter.kt
> +        val rightList = if (list1.size < list2.size) list1 else list2
мб чуть понятнее, кто левый и кто правый, если написать в одну строчку:
`        val (leftList, rightList) = if (list1.size < list2.size) list2 to list1 else list1 to list2
`

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorter.kt
> +    useParallelMerge: Boolean
а зачем тебе вообще useParallelMerge? у тебя это коррелирует с recursionLimit, если он <= 0 ты запускаешь обычный merge и все

2021-05-04 18:35 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorter.kt
> +        options.semaphore.acquireUninterruptibly()
с семафором интересная идея, но ты уверен, что у тебя в merge надо ограничивать работающие потоки как-то? ты запускаешь merge после того, как у тебя закончили работать потоки в mergeSort, а в mergeSort ты всегда создаешь ровно столько потоков, сколько допускает уровень рекурсии, поэтому по идее у тебя одновременно не может работать больше потоков
поэтому не очень понимаю, зачем тут семафор?

2021-05-04 18:35 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeRunnableTest.kt
> +    fun runParallel(expected: List<Int>, list1: List<Int>, list2: List<Int>) {
хочется с разным количеством потоков тоже протестировать

2021-05-04 18:35 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeRunnableTest.kt
> +            Arguments.of(listOf(1, 2, 3, 4), listOf(1, 3), listOf(2, 4)),
списки побольше тоже хочется протестировать, списки в 5 элементов как-то несерьезно, там merge даже разгуляться негде

2021-05-04 18:35 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeRunnableTest.kt
> +    fun runParallel(expected: List<Int>, list1: List<Int>, list2: List<Int>) {
ну и те же комментарии ко второму файлу с тестами

2021-05-04 18:35 UTC, elena-lyulina commented on src/test/kotlin/homework6/MergeRunnableTest.kt
> +            Arguments.of(listOf(1, 2, 3, 4), listOf(1, 3), listOf(2, 4)),
ну и те же комментарии ко второму файлу с тестами

2021-05-05 12:14 UTC, ubuntuegor commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +import tornadofx.launch
Хахах, только недавно отключил эту настройку в идее, потому что detekt жалуется на wildcard imports. Но в целом мне тоже кажется что тут wildcard более чем уместен.

2021-05-05 12:16 UTC, ubuntuegor commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +    private fun createRandomList(size: Int) = (1..size).shuffled()
А... чем лучше? 🧐
В тестах мне кажется тоже будет наглядно сделать assert equals по sort(range.shuffled()) и range

2021-05-05 12:32 UTC, ubuntuegor commented on src/main/kotlin/homework6/MergeSorter.kt
> +    useParallelMerge: Boolean
useParallelMerge отвечает за то, использовать ли параллельный мерж вообще, даже если recursionLimit > 0. Просто оставил, чтобы на графиках посмотреть, как использование параллельного мержа может влиять на время сортировки. Вот например разница на графике:
![image](https://user-images.githubusercontent.com/6959139/117140347-fa99c780-adb5-11eb-98b1-709ca9875ad5.png)

2021-05-05 12:43 UTC, ubuntuegor commented on src/main/kotlin/homework6/MergeSorter.kt
> +        options.semaphore.acquireUninterruptibly()
Ну, в том и логика, что из-за рекурсии сразу же создается столько потоков, сколько позволяет recursionLimit, а это может быть достаточно большим числом. Так что мне показалось разумным ограничить число потоков, непосредственно выполняющих какую-то работу (в данном случае merge, так как mergeSort кроме запуска других потоков ничего по сути не делает).
На самом деле, в процессе написания этой домашки я просто сначала добавил семафор, так как думал что именно им нужно число потоков ограничивать, и только потом сделал лимит рекурсии, чтобы не создавалось очень большое число потоков. В принципе, если посмотреть на графики по working threads, то семафор действительно ни на что не влияет. Разве что видно замедление, если стоит ограничение в 1 работающий поток.

2021-05-05 12:44 UTC, ubuntuegor commented on src/main/kotlin/homework6/MergeSorter.kt
> +        options.semaphore.acquireUninterruptibly()
Так что наверное его можно и удалить)

2021-05-13 15:58 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSortChartsApp.kt
> +import tornadofx.launch
дааа, там насчет wildcart imports идут споры, например, https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

но тут кажется не тот случай совсем и они уместны, да

2021-05-13 16:06 UTC, elena-lyulina commented on src/main/kotlin/homework6/MergeSorter.kt
> +    useParallelMerge: Boolean
как-то странно выглядит надпись "32 created, normal merge", почему у тебя вообще создаются потоки при нормальном слиянии? что-то не то, так что все равно кажется, что useParalellMerge странно звучит, так как все регулируется уровнем рекурсии по идее

2021-05-13 16:09 UTC, elena-lyulina requested changes
Почти все, там только все еще остался коммент про useParallelMerge
ну и конфликты хочется поправить

2021-05-27 21:24 UTC, elena-lyulina approved these changes
супер, спасибо!

2021-05-27 21:24 UTC, merged