Homework 1, task 1. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #2
Opened 2021-02-28 23:24 UTC by ubuntuegor

2021-03-01 09:24 UTC, nbirillo requested changes

2021-03-01 09:24 UTC, nbirillo commented on src/main/kotlin/homework1/task1.kt
> +    if (n == null || n < 1) {
Для 0 можно и посчитать

2021-03-01 09:24 UTC, nbirillo commented on src/main/kotlin/homework1/task1.kt
> +        return
Может тогда лучше ошибку бросить? Вместо пустого `return`. см. `error()` или `throw`

2021-03-01 10:24 UTC, ubuntuegor commented on src/main/kotlin/homework1/task1.kt
> +        return
Мне казалось исключения как раз не должны вылезать в конечном итоге юзеру, тем более в мейне их бросать
Соответственно все предвиденные ошибки ловить и выводить юзеру в более дружелюбной форме, как тут принтом

2021-03-01 10:29 UTC, nbirillo commented on src/main/kotlin/homework1/task1.kt
> +        return
Ну ты можешь кинуть ошибку какую-то с осмысленным названием и передать туда сообщение, которое будет в дружелюбной форме говорить пользователю, что он сделал что-то не то. Просто это ошибочная ситуация, но ты все равно завершаешь программу без ошибок (я про status code). Если ты не хочешь кидать исключение, но это аварийное завершение (а это так, так как ты не обрабатываешь это дополнительно, а выходишь с программы), тогда нужно завершать программу например как-то [так](https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/main/kotlin/kotlin/system/Process.kt#L27)

2021-03-02 17:23 UTC, nbirillo requested changes
Почти готово

2021-03-02 17:23 UTC, nbirillo commented on src/main/kotlin/common/error/error.kt
> +fun die(message: String): Nothing {
Довольно странное название) Назови как-то более понятно - `safeExit` или еще как

2021-03-02 17:49 UTC, ubuntuegor commented on src/main/kotlin/common/error/error.kt
> +fun die(message: String): Nothing {
Назвал по памяти из PHP с идентичным поведением https://www.php.net/manual/en/function.die.php
Ну тогда `exitWithError` надеюсь понятно будет (раз пакет common.error, и сообщение печатается с префиксом `ERROR`)

2021-03-04 11:58 UTC, nbirillo approved these changes
Зачтено

2021-03-04 11:58 UTC, merged