Homework 8, task 1. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #21
Opened 2021-05-19 07:48 UTC by ubuntuegor

Без онлайна. Есть только жалкая попытка в онлайн: https://github.com/ubuntuegor/spbu_2020_kotlin_homeworks/compare/hw8task1...hw8task1dev
Ну точнее, там по идее все должно работать, но не работает. Возможно, потому что я не нашел удобного способа для обмена информацией между корутинами, и все получилось слегка костыльно

2021-05-19 07:50 UTC, ubuntuegor commented
Зато красиво)

2021-05-24 10:53 UTC, SpirinEgor requested changes
Получилось действительно очень красиво. Пока что приз за самую дизайнерскую реализацию уходит тебе. Можешь даже на будущее вообще вынести в отдельный репо, сделать ридми и хвастаться :)

Но с сервером надо добить. Кажется, что твоя архитектура в целом позволяет это. Если я правильно все осознал, то необходимо просто реализовать еще одного Player. И немного прибраться в контроллере в `makeMove`. Я не заглядывал в ту ветку, лучше напиши мне или Насте, какие у тебя проблемы/вопросы. Постараемся решить :)

2021-05-24 10:53 UTC, SpirinEgor commented on src/main/kotlin/homework8/controllers/GameController.kt
> +        if (game is TwoControlledPlayersGame) {
Вот тут не хватает абстракции. У тебя по сути в этой функции заложено определение типа игры. Хотя контроллер вообще про это не должен знать. Аналогично с сетевым режимом, тебе придется здесь еще один else дописывать и там какую-то логику обозначать. Все это должно быть запрятано в модель игры, которая сама уже определяет как этот самый ход сделать и что будет дальше.

2021-05-24 10:53 UTC, SpirinEgor commented on src/main/kotlin/homework8/games/Game.kt
> +abstract class Game {
Не могу сказать, что это отличное решение сделать абстрактный класс с 6 вложенными классами и всего 2 абстрактными полями. К тому же они protected, не очень понял зачем...

2021-05-24 10:53 UTC, SpirinEgor commented on src/main/kotlin/homework8/views/GameView.kt
> +                        GameController.State.ENDED -> "Opponent has left."
Так как это Enum, то можно было сделать чуть красивее
```
enum class State(message: String) {
    READY("Waiting for opponent...")
    ...
}
```
Тогда вместо ужасного when тут ты просто нашишешь `it.message`

2021-05-28 02:04 UTC, ubuntuegor commented
Добавил онлайн, поправил прошлые комментарии. @nbirillo тегаю на всякий случай
Ещё раскатал сервер на `ws://limitless-garden-50112.herokuapp.com/game`, можно тру онлайн проверить)

2021-05-29 16:25 UTC, SpirinEgor approved these changes
Огонь! Очень понравилась твоя игра. Архитектурно, не очень нравится, что в контроллер много логики положил. У тебя они отвечают и за контент представления, и за логику игры, и за сетевое подключение. Тут очень легко мыслить так: если я хочу портировать клиент на телефон, то сколько кода придется переписывать? В идеальном мире, ты просто пишешь интерфейс для экрана и переиспользуешь компоненты, которые знают как подключаться по сети и вести игру. У тебя так просто не получится.

2021-05-31 11:13 UTC, nbirillo approved these changes
Серверная часть мне тоже понравилась, не супер идеально, но вполне себе хорошо. Так что с моей стороны тоже апрув

2021-05-31 13:07 UTC, merged