Homework 1, task 2. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #3
Opened 2021-02-28 23:24 UTC by ubuntuegor

2021-03-01 09:30 UTC, nbirillo requested changes

2021-03-01 09:30 UTC, nbirillo commented on src/main/kotlin/homework1/task2.kt
> +        return
Как и в первой задаче - лучше тогда ошибку кинуть.

2021-03-01 09:30 UTC, nbirillo commented on src/main/kotlin/homework1/task2.kt
> +fun main() {
С двумя пустыми строчками будет немного не очень
![image](https://user-images.githubusercontent.com/8993915/109477785-7f502880-7a89-11eb-9129-68ddca3a60d1.png)
(или если только первая пустая)

2021-03-01 09:30 UTC, nbirillo commented on src/main/kotlin/homework1/task2.kt
> +fun countOccurrences(needle: String, haystack: String): Int {
(чисто стилистически, но смотрится приятнее). Лучше сделать функцию-расширение для класса `String`, куда будет подаваться вторая строка, так читать понятнее обычно:
```
fun String. countOccurrences(substr: String): Int { ... }
```
и вызывать тогда в твоем случае
```
haystack.countOccurrences(needle) 
```
тут сразу интуитивно понятно, в какой строке какую искать и выглядит красиво. Но это уже смотри сам как тебе нравится больше, у тебя названия не string1, string2, так что в целом тоже понятно что происходит

2021-03-02 17:26 UTC, nbirillo requested changes

2021-03-02 17:26 UTC, nbirillo commented on src/main/kotlin/common/error/error.kt
> +fun die(message: String): Nothing {
В другом пр-е уже сказала про имя

2021-03-02 17:26 UTC, nbirillo commented on src/main/kotlin/homework1/task2.kt
> +fun main() {
Действительно ли ожидается такое поведение?
![image](https://user-images.githubusercontent.com/8993915/109688566-751b5080-7b95-11eb-91fc-1f0d4053858b.png)

2021-03-02 17:56 UTC, ubuntuegor commented on src/main/kotlin/homework1/task2.kt
> +fun main() {
Ну, перед словом, после слова, и между буквами...
Но если вы ожидаете другого поведения, то сейчас что-нибудь придумаю)

2021-03-04 12:00 UTC, nbirillo approved these changes
Зачтено!

2021-03-04 12:00 UTC, merged