Homework 1, task 3. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #4
Opened 2021-02-28 23:25 UTC by ubuntuegor

2021-03-01 10:01 UTC, nbirillo requested changes

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/PerformedCommandStorage.kt
> +package homework1.classes
Немного странно называть пакет classes, так обычно не делают. Можно оставить просто вложенные папки

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/PerformedCommandStorage.kt
> +    private val _storage = mutableListOf<Int>()
Честно говоря ни разу не видела, чтобы помечали `_` приватные поля. Это же не питон. Почитай стайгайд еще раз)

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/exceptions/InvalidMoveIndexException.kt
> +class InvalidMoveIndexException : Exception()
У нас еще не было темы исключений, но просто нет смысла плодить кучу своих исключений (так как есть много стандартных, которые подходят почти под все кейсы). Более того, не нужно создать новый класс ошибки только ради названия, ты же даже ничего не переопределяешь. Поищи что-нибудь стандартное для себя, пожалуйста. Тот же комментарий про второй класс с эксепшеном

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/actions/AppendToEndAction.kt
> +class AppendToEndAction(val value: Int) : Action {
Кажется, что ты забыл сделать `value` `private`  (это всех действий касается)

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/actions/MoveElementAction.kt
> +        if (from !in list.indices || to !in list.indices) throw InvalidMoveIndexException()
Ну про свой класс ошибки я уже написала выше, но есть еще одно замечание - кидать ошибки нужно с осмысленным сообщением

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/actions/MoveElementAction.kt
> +        list.add(to, temp)
Можно короче: `list[to] = list[from].also { list[from] = list[to] }`

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/actions/MoveElementAction.kt
> +        list.add(to, temp)
А еще будет очень красиво, если ты сделаешь функцию-расширение:
```
private fun MutableList<Int>.moveListElement(from: Int, to: Int) {...}
```
Если ты сделаешь ее тут (внутри класса), то она будет доступна внутри класса, а выглядеть будет красивее))

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/classes/PerformedCommandStorage.kt
> +        val lastAction = _performedActions.last()
Кинет `NoSuchElementException`, если элементов нет

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/common/io.kt
> +    return readLine()?.toIntOrNull() ?: throw InvalidInputException()
Сообщение об ошибке добавь + не используй тут свой класс исключений

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +package homework1
Очень странно смотрится этот файл, ты во все функции передаешь logStorage. Кажется, лучше сделать `object`, там сделать поле например и там сделать `main`. А то это больше похоже на питон, чем на котлин

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +package homework1
Причем можно внутри этого `object` сделать расширения функций `PerformedCommandStorage`, чтобы их можно было красиво вызывать

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +}
Такие функции лучше писать сокращенно (без доп переменных). Например так:
```
fun promptForAppendToStartAction() = AppendToStartAction(promptInt("Value to append to start: "))
```
Я не указала тип выходного значения, потому что он тут итак очевиден

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +
О, ты тут обрабатываешь. Но кажется, что лучше просто проинформировать пользователя внутри стораджа, чтобы не нужно было как-то вне об этом заботиться

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +    println()
Может быть ты лучше будешь возвращать строки из функци и печатать тут все через $? Ну или тогда добавишь новую строку где нужно в самих функциях печати. А то честно говоря странно выглядит

2021-03-01 10:01 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +fun programLoop(logStorage: PerformedCommandStorage): Boolean {
Название странное) может `applyActions` или типа того. В целом функции лучше называть с глаголов

2021-03-01 10:30 UTC, ubuntuegor commented on src/main/kotlin/homework1/classes/PerformedCommandStorage.kt
> +    private val _storage = mutableListOf<Int>()
В Coding conventions и прочитал) https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties
Ну тут только случай со storage по большому счету, для performedActions мб и не надо нижнего подчеркивания

2021-03-01 10:35 UTC, ubuntuegor commented on src/main/kotlin/homework1/task3.kt
> +
Мне кажется storage сам по себе пользователю ничего сообщать не должен (в смысле вызывать print-ы и т.п.)

2021-03-01 10:36 UTC, nbirillo commented on src/main/kotlin/homework1/classes/PerformedCommandStorage.kt
> +    private val _storage = mutableListOf<Int>()
ну да, тут скорее было про `_performedActions`) `_storage` можешь оставить

2021-03-01 10:39 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +
Просто в данном случае это кажется скорее дефолтным поведением, чем каким-то внешним. Но можешь так оставить тогда, в целом это нормально, что он Throwable
Но в данном случае я бы тогда сразу (не дожидаясь второго дз) написала это в комментариях у `undoLastAction` функции, чтобы понимать, что ты понимаешь, что это может произойти

2021-03-01 10:40 UTC, ubuntuegor commented on src/main/kotlin/homework1/classes/actions/AppendToEndAction.kt
> +class AppendToEndAction(val value: Int) : Action {
Ну я видел предложение idea-и, но это как я понимаю уже read-only значение, и мне кажется имеет смысл держать их публичными, чтобы можно было идентифицировать экшны одинакового типа между собой (хоть это сейчас и не используется)

2021-03-01 10:56 UTC, ubuntuegor commented on src/main/kotlin/homework1/task3.kt
> +package homework1
А например сделать logStorage глобальным очень плохо будет? Один из плюсов котлина же как раз что он разные парадигмы поддерживает. По структуре кода вроде одно и то же будет, что если всё в object завернуть, что не заворачивать и оставить глобальным. Во втором случае даже на уровень вложенности меньше

2021-03-01 11:00 UTC, nbirillo commented on src/main/kotlin/homework1/classes/actions/AppendToEndAction.kt
> +class AppendToEndAction(val value: Int) : Action {
Что значит экшены одинакового типа? `value` же не тип хранит, а значение, которое добавляется\удаляется. А тип `AppendToEndAction` :) Я пока что не очень представляю ситуацию, когда это значение может быть не публичным) но если приведешь более убедительный пример, то будет хорошо

2021-03-01 11:04 UTC, nbirillo commented on src/main/kotlin/homework1/task3.kt
> +package homework1
Глобальные переменные в целом так себе. Часто делают функции вне классов\объектов и это удобно. Тут еще просто скорее даже не в котлине дело, а в ООП. У тебя же по сути это просто сущность, которая что-то делает, оперируя своим стораджем (это может быть объект или класс) и у которой есть свой набор действий. А если ты просто пишешь это внутри одного файла (еще и с глобальными переменными), то это разрозненные кусочки. Обычно так (просто набор функций в одном файле) пишут какие-нибудь util функции например, потому что они очевидно не являются частью одного целого и их можно не оборачивать в объект только ради того, чтобы они не были просто функциями

2021-03-01 11:21 UTC, ubuntuegor commented on src/main/kotlin/homework1/classes/actions/AppendToEndAction.kt
> +class AppendToEndAction(val value: Int) : Action {
Например, у нас есть два объекта `AppendToEndAction`. Если поле value приватное, то мы извне каждое из них можем описать лишь как "добавить в конец" и "добавить в конец", и между собой никак не отличим (разве что по name но это как-то костыльно). Когда мы описываем такие действия, нам обычно интересно, что именно мы добавляем в конец: "добавить 5 в конец", "добавить 36 в конец".

2021-03-01 11:57 UTC, nbirillo commented on src/main/kotlin/homework1/classes/actions/AppendToEndAction.kt
> +class AppendToEndAction(val value: Int) : Action {
ну сделай тогда поле `description`, которое будет иметь эту информацию или типа того) кажется, что давать доступ только из-за этого к полю немного странно

2021-03-01 11:58 UTC, nbirillo commented on src/main/kotlin/homework1/classes/actions/MoveElementAction.kt
> +        list.add(to, temp)
Upd: там я меняла местами переменные, это можно игнорировать (первый комментарий)

2021-03-02 17:30 UTC, nbirillo requested changes
Один небольшой комментарий остался

2021-03-02 17:30 UTC, nbirillo commented on src/main/kotlin/homework1/classes/PerformedCommandStorage.kt
> +package homework1
Недостаточно здесь убрать `classes`, нужно саму папку тоже убрать

2021-03-04 12:02 UTC, nbirillo approved these changes
Зачтено!

2021-03-04 12:02 UTC, merged