Homework 3, task 3. Куковеров Егор
ubuntuegor/spbu_2020_kotlin_homeworks pull request #9
Opened 2021-03-19 00:39 UTC by ubuntuegor

Тестовый конфиг: https://pastebin.com/Jq5MB7jP
Параметры запуска: `generateTest.yaml src/test/kotlin`

2021-03-22 17:41 UTC, cupertank requested changes
В целом очень очень хорошо, но я хотел бы ещё видеть ещё один вид тестов. Сделай отдельную папку для них, и в ней сделай несколько подпапок где будут лежать config.yaml и expected.kt, сравни что у тебя сгенерируется по конфигу и что лежит ожидаемое. Ожидаемое лучше ручками написать))

2021-03-22 17:41 UTC, cupertank commented on src/main/kotlin/homework3/TestGeneratorConfig.kt
>      @SerialName("class-name")
Кажется, что у вас в задании было "package name" и "class name" без тире))

2021-03-22 17:41 UTC, cupertank commented on src/main/kotlin/homework3/TestGenerator.kt
> +    private val testAnnotation = ClassName("org.junit.jupiter.api", "Test")
Это можно сделать статической переменной или просто заинлайнить в функцию, где оно используется. Просто в каждом экземпляре этого класса хранить нет смысла.

2021-03-23 15:59 UTC, ubuntuegor commented on src/main/kotlin/homework3/TestGeneratorConfig.kt
>      @SerialName("class-name")
Никогда не видел, чтобы в конфигах были имена полей с пробелами, но ок)

2021-03-29 15:07 UTC, cupertank requested changes
Написано очень хорошо, если доделаешь до 00:00 поставлю полный балл

2021-03-29 15:07 UTC, cupertank commented on src/test/kotlin/homework3/Task3KtTest.kt
> +                TestGeneratorConfigTest::class.java.getResource("validation/test3/config.yaml").path
У тебя очень много дублирующего кода связанного с чтением из ресурсов. Оставь просто пути в аргументах, а чтение унеси в сам тест, иначе это просто нечитабельно как-то....

2021-03-29 15:07 UTC, cupertank commented on src/test/kotlin/homework3/TestGeneratorTest.kt
> +                TestGeneratorTest::class.java.getResource("generatedTests/test1.kt").readText(),
тут аналогичная проблема. просто оставь путь, читай в тесте

2021-03-29 15:07 UTC, cupertank commented on src/test/kotlin/homework3/Task3KtTest.kt
> +                TestGeneratorConfigTest::class.java.getResource("validation/test3/config.yaml").path
И ты меня не совсем верно понял. Я хотел чтобы у тебя каждый аргумент был "test1", "test2" и тд...
В самом тесте ты бы обращался просто в ресурсы с по этому "test1" и брал из папки expect.kt и config.yaml и отрабатывал.

2021-03-29 15:07 UTC, cupertank commented on src/test/kotlin/homework3/Task3KtTest.kt
> +                TestGeneratorConfigTest::class.java.getResource("validation/test3/config.yaml").path
Первые два ты можешь вообще убрать отсюда, пускай они у тебя используются в других тестах

2021-03-29 15:07 UTC, cupertank commented on src/test/kotlin/homework3/Task3KtTest.kt
> +                TestGeneratorConfigTest::class.java.getResource("validation/test3/config.yaml").path
Тут я хочу чтобы у тебя было три аргумента "test1", "test2" и "test3", потом ты в самом тесте берешь из этой папки "expect.kt" и "config.yaml", генерируешь и сравниваешь. Именно поэтому я попросил унифицировать expect.kt и config.yaml

2021-03-29 16:53 UTC, cupertank approved these changes

2021-03-29 16:54 UTC, merged